#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Export all vars

export $(dbus-launch)
eval "$(guix package --search-paths \
-p $HOME/.config/guix/current \
-p $HOME/.guix-home/profile \
-p $HOME/.guix-profile \
-p $HOME/.nix-profile/ \
-p /run/current-system/profile)"

# Prepend setuid programs.
export PATH=/run/setuid-programs:$PATH

set -o allexport

# Adds `~/.local/bin` to $PATH
PATH="$PATH:${$(find ~/.local/bin -type d,l -printf %p:)%%:}"
PATH=$PATH:/home/javier/.local/share/nvim/mason/bin
# PATH=$PATH:~/.local/bin/scripts

# Prepend setuid programs.

unsetopt PROMPT_SP

# Default programs:
EDITOR="nvim"
TERMINAL="footclient"
BROWSER="firefox"
GPG_TTY=$(tty)

# ~/ Clean-up:
XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_BIN_HOME=$HOME/.local/bin/scripts
# XDG_BIN_HOME=$(find ~/.local/bin -type d -type ! l -printf %p:)
XDG_CACHE_HOME="$HOME/.cache"
XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)
XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
XCURSOR_THEME="Bibata-Modern-Classic"
LESSHISTFILE="-"
WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
TMUX_TMPDIR="$XDG_RUNTIME_DIR"
HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
PIPEWIRE_RUNTIME_DIR="/run/user/1000"
BAT_THEME="gruvbox-dark"
# GI_TYPELIB_PATH=/run/current-system/sw/lib/girepository-1.0:$HOME/.nix-profile/lib/girepository-1.0
# Guix
GUIX_PROFILE="/home/javier/.guix-profile"
. "$GUIX_PROFILE/etc/profile"
GUIX_LOCPATH="$HOME/.guix-profile/share/locale"

# Nix
NODE_PATH="/home/javier/.guix-profile/lib/node_modules${NODE_PATH:+:}$NODE_PATH"
NIX_REMOTE=daemon
C_INCLUDE_PATH="/home/javier/.guix-profile/include${C_INCLUDE_PATH:+:}$C_INCLUDE_PATH"
CPLUS_INCLUDE_PATH="/home/javier/.guix-profile/include${CPLUS_INCLUDE_PATH:+:}$CPLUS_INCLUDE_PATH"
LIBRARY_PATH="/home/javier/.guix-profile/lib${LIBRARY_PATH:+:}$LIBRARY_PATH"
NIX_PROFILES="/nix/var/nix/profiles/default $HOME/.nix-profile"
for i in $NIX_PROFILES; do
    export PATH="${PATH}:${i}/bin"
done
NIXPKGS_ALLOW_UNFREE=1
NIX_CONFIG="experimental-features = nix-command flakes"
# XDG_CURRENT_DESKTOP=wayland

# NNN
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
NNN_BMS='w:~/pics/walls/;d:~/.dotfiles/home/;p:~/.local/src/;'
NNN_USE_EDITOR=1
NNN_FIFO=/tmp/nnn.fifo

NNN_OPENER="/home/javier/.local/bin/scripts/nuke"
IMAGEVIEWER="sxiv"
NNN_PLUG='p:imgview;o:fzopen;d:diffs'
NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"

# Other program settings:
DICS="/usr/share/stardict/dic/"
# SUDO_ASKPASS="$HOME/.local/bin/scripts/tofipass"
# DOAS_ASKPASS="$HOME/.local/bin/scripts/tofi-pass.sh"
# FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#282828
  --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
  --color=prompt:#458588,spinner:#af5fff,pointer:#af5fff,header:#87afaf
  --color=gutter:-1,border:#262626,label:#aeaeae,query:#d9d9d9
  --border="bold" --border-label="" --preview-window="border-bold" --prompt="❯❯ "
  --marker="*" --pointer="->" --separator="─" --scrollbar="│"
  --layout="reverse-list" --info="right" --multi
  --height=10
  '
LESS=-R
LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
LESS_TERMCAP_me="$(printf '%b' '[0m')"
LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
LESS_TERMCAP_se="$(printf '%b' '[0m')"
LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
LESS_TERMCAP_ue="$(printf '%b' '[0m')"
LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
_JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

# Start wayland server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && exec Hyprland
# [ "$(tty)" = "/dev/tty1" ] && exec dwl
xrdb ~/.config/.Xdefaults
# [ "$(tty)" = "/dev/tty1" ] && exec sway
