[pyprland]
plugins = [
  "scratchpads",
  "shortcuts_menu",
  "expose",
  "layout_center"
]

# [scratchpads.term]
# animation = "fromTop"
# command = "foot -a scratchpad"
# lazy = true
# size = "75% 60%"
# max_size = "1920px 100%"
# margin = 50

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class scratchpad"
lazy = true
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.music_player]
animation = "fromRight"
# command = "foot -a scratchpad -e ncmpcpp"
command = "kitty --class scratchpad -e ncmpcpp"
class = "scratchpad"
lazy = true
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.file_manager]
animation = "fromLeft"
# command = "foot -a scratchpad -e yazi"
command = "kitty --class scratchpad -e nnn -cH"
class = "scratchpad"
lazy = true
size = "75% 60%"
position = "5% 10%"
max_size = "1920px 100%"
margin = 50

[scratchpads.tomb]
animation = "fromBottom"
command = "kitty --class scratchpad -e tmount.sh"
lazy = true
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.emacs]
animation = "fromTop"
command = "emacs"
class = "Emacs"
lazy = true

# Shorcuts_menu 
[shortcuts_menu]
engine = "tofi"
# parameters = "-p '[prompt] 🍰 ' -dmenu -matching fuzzy -i"
command_start = "💀 "

[shortcuts_menu.entries]
# "Tombs" = "pypr toggle tomb && hyprctl dispatch bringactivetotop && $updateWaybar"
# "Mount Devices" = "hypr-scratchpads fzmount"
# "Open telegram" = "telegram-desktop"

# layout_center.
[layout_center]
style = ["opacity 1", "bordercolor rgb(FFFF00)"]
margin = 0
