# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	{ on = [ "j" ], run = [ "plugin arrow --args=1"],  desc = "Move selection downwards, or wrap." },
	{ on = [ "k" ], run = [ "plugin arrow --args=-1"], desc = "Move selection upwards, or wrap." },
	{ on = [ "l" ], run = [ "plugin smart-enter ", "escape --visual --select" ], desc = "Enter the child directory, or open file." },
	{ on = [ "L" ], run = "plugin smart-enter --args='detatch'", desc = "Open in new window." },
	{ on = [ "=" ], run = """
        shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm
    """, desc = "chmod" },
	{on = [ "p" ], run = ["plugin smart-paste"], desc = "Paste into the hovered directory" },
	{on = [ "g", "w" ], run = ["cd ~/webdev/jpachecoxyz.github.io/"], desc = "Go to my web deployment" },
	{on = [ "g", "c", ], run = ["cd ~/.config"], desc = "Go to XDG_CONIG." },
	{on = [ "g", "b", ], run = ["cd ~/.local/bin"], desc = "Go to bin folder." },
	{on = [ "g", "e", ], run = ["cd ~/.emacs.d"], desc = "Go to emacs folder." },
	{on = [ "g", "x", ], run = ["cd ~/.dotfiles/nix"], desc = "Go to my nix configuration." },
]

[input]
prepend_keymap = [
	{on = [ "<Esc>" ], run = ["close"], desc = "Cancel input" },
]
