# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#83a598" }

# Hovered
hovered         = { fg = "#282828", bg = "#83a598" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b8bb26", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#282828", bg = "#504945" }
tab_inactive = { fg = "#a89984", bg = "#3c3836" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#665c54" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Mode
mode_normal = { fg = "#282828", bg = "#A89984", bold = true }
mode_select = { fg = "#282828", bg = "#b8bb26", bold = true }
mode_unset  = { fg = "#282828", bg = "#d3869b", bold = true }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#504945" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#bdae93" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#504945" }
active   = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#504945" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#83a598" }
rest            = { fg = "#928374" }
desc            = { fg = "#fe8019" }
separator       = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#fe8019" }
exec    = { fg = "#83a598" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#83a598" },

    # Videos
    { mime = "video/*", fg = "#b8bb26" },
    { mime = "audio/*", fg = "#b8bb26" },

    # Archives
    { mime = "application/zip",             fg = "#fe8019" },
    { mime = "application/gzip",            fg = "#fe8019" },
    { mime = "application/x-tar",           fg = "#fe8019" },
    { mime = "application/x-bzip",          fg = "#fe8019" },
    { mime = "application/x-bzip2",         fg = "#fe8019" },
    { mime = "application/x-7z-compressed", fg = "#fe8019" },
    { mime = "application/x-rar",           fg = "#fe8019" },

    # Fallback
    { name = "*", fg = "#a89984" },
    { name = "*/", fg = "#83a598" }
]

# : }}}

[icon]

rules = [
    # Programming
    { name = "*.cpp"  , text = "", fg = "#519aba" },
    { name = "*.css"  , text = "", fg = "#42a5f5" },
    { name = "*.c"    , text = "", fg = "#599eff" },
    { name = "*.fish" , text = "" },
    { name = "*.go"   , text = "", fg = "#519aba" },
    { name = "*.hpp"  , text = "", fg = "#a074c4" },
    { name = "*.h"    , text = "", fg = "#a074c4" },
    { name = "*.htm"  , text = "", fg = "#e44d26" },
    { name = "*.html" , text = "", fg = "#e44d26" },
    { name = "*.java" , text = "", fg = "#cc3e44" },
    { name = "*.js"   , text = "", fg = "#F1F134" },
    { name = "*.jsx"  , text = "", fg = "#20c2e3" },
    { name = "*.lua"  , text = "", fg = "#51a0cf" },
    { name = "*.nix"  , text = "", fg = "#7ab1db" },
    { name = "*.php"  , text = "" },
    { name = "*.rb"   , text = "" },
    { name = "*.rs"   , text = "", fg = "#dea584" },
    { name = "*.scss" , text = "" },
    { name = "*.sh"   , text = "", fg = "#4d5a5e" },
    { name = "*.swift", text = "" },
    { name = "*.ts"   , text = "", fg = "#519aba" },
    { name = "*.tsx"  , text = "" },
    { name = "*.vim"  , text = "" },
    { name = "*.vue"  , text = "󰡄" },
    { name = "*.py"   , text = "", fg = "#ffbc03" },
    { name = "*.pyc"  , text = "", fg = "#ffe291" },

    # Text
    { name = "*.txt"     , text = "", fg = "#bbbbbb" },
    { name = "*.csv"     , text = "", fg = "#89e051" },
    { name = "*.json"    , text = "", fg = "#cbcb41" },
    { name = "*.conf"    , text = "", fg = "#6d8086" }, # Configuration
    { name = "*.ini"     , text = "", fg = "#6d8086" },
    { name = "*.yaml"    , text = "", fg = "#6d8086" },
    { name = "*.yml"     , text = "", fg = "#6d8086" },
    { name = "*.toml"    , text = "", fg = "#6d8086" },
    { name = "*.org"     , text = "", fg = "#77aa99" },
    { name = "*.tex"     , text = "󰙩", fg = "#3d6117" }, # Plaintext typesetting
    { name = "*.typ"     , text = "󰙩", fg = "#0e606a" },
    { name = "*.markdown", text = "", fg = "#519aba" }, # Markdown
    { name = "*.md"      , text = "", fg = "#519aba" },
    { name = "*.mdx"     , text = "", fg = "#519aba" },
    { name = "*.rmd"     , text = "", fg = "#519aba" },

    # Archives
    { name = "*.7z"  , text = "" },
    { name = "*.ace" , text = "" },
    { name = "*.alz" , text = "" },
    { name = "*.arc" , text = "" },
    { name = "*.arj" , text = "" },
    { name = "*.bz2" , text = "" },
    { name = "*.bz"  , text = "" },
    { name = "*.cab" , text = "" },
    { name = "*.cpio", text = "" },
    { name = "*.deb" , text = "" },
    { name = "*.dwm" , text = "" },
    { name = "*.dz"  , text = "" },
    { name = "*.ear" , text = "" },
    { name = "*.esd" , text = "" },
    { name = "*.gz"  , text = "" },
    { name = "*.jar" , text = "" },
    { name = "*.lha" , text = "" },
    { name = "*.lrz" , text = "" },
    { name = "*.lz4" , text = "" },
    { name = "*.lzh" , text = "" },
    { name = "*.lzma", text = "" },
    { name = "*.lzo" , text = "" },
    { name = "*.lz"  , text = "" },
    { name = "*.rar" , text = "" },
    { name = "*.rpm" , text = "" },
    { name = "*.rz"  , text = "" },
    { name = "*.sar" , text = "" },
    { name = "*.swm" , text = "" },
    { name = "*.t7z" , text = "" },
    { name = "*.tar" , text = "" },
    { name = "*.taz" , text = "" },
    { name = "*.tbz2", text = "" },
    { name = "*.tbz" , text = "" },
    { name = "*.tgz" , text = "" },
    { name = "*.tlz" , text = "" },
    { name = "*.txz" , text = "" },
    { name = "*.tzo" , text = "" },
    { name = "*.tzst", text = "" },
    { name = "*.tz"  , text = "" },
    { name = "*.war" , text = "" },
    { name = "*.wim" , text = "" },
    { name = "*.xz"  , text = "" },
    { name = "*.zip" , text = "" },
    { name = "*.zoo" , text = "" },
    { name = "*.zst" , text = "" },
    { name = "*.z"   , text = "" },

    # Images
    { name = "*.bmp"  , text = "" }, # Lossless
    { name = "*.gif"  , text = "" },
    { name = "*.png"  , text = "" },
    { name = "*.tiff" , text = "" },
    { name = "*.webp" , text = "" },
    { name = "*.jpeg" , text = "" }, # Lossy
    { name = "*.jpg"  , text = "" },
    { name = "*.mjpeg", text = "" },
    { name = "*.mjpg" , text = "" },
    { name = "*.mng"  , text = "" },
    { name = "*.pbm"  , text = "" },
    { name = "*.pcx"  , text = "" },
    { name = "*.pgm"  , text = "" },
    { name = "*.ppm"  , text = "" },
    { name = "*.svg"  , text = "" },
    { name = "*.svgz" , text = "" },
    { name = "*.tga"  , text = "" },
    { name = "*.tif"  , text = "" },
    { name = "*.xbm"  , text = "" },
    { name = "*.xpm"  , text = "" },

    # Movies
    { name = "*.asf" , text = "" },
    { name = "*.avi" , text = "" },
    { name = "*.cgm" , text = "" },
    { name = "*.dl"  , text = "" },
    { name = "*.emf" , text = "" },
    { name = "*.flc" , text = "" },
    { name = "*.fli" , text = "" },
    { name = "*.flv" , text = "" },
    { name = "*.gl"  , text = "" },
    { name = "*.m2v" , text = "" },
    { name = "*.m4v" , text = "" },
    { name = "*.mkv" , text = "" },
    { name = "*.mov" , text = "" },
    { name = "*.mp4" , text = "" },
    { name = "*.mp4v", text = "" },
    { name = "*.mpeg", text = "" },
    { name = "*.mpg" , text = "" },
    { name = "*.nuv" , text = "" },
    { name = "*.ogm" , text = "" },
    { name = "*.ogv" , text = "" },
    { name = "*.ogx" , text = "" },
    { name = "*.qt"  , text = "" },
    { name = "*.rm"  , text = "" },
    { name = "*.rmvb", text = "" },
    { name = "*.vob" , text = "" },
    { name = "*.webm", text = "" },
    { name = "*.wmv" , text = "" },
    { name = "*.xcf" , text = "" },
    { name = "*.xwd" , text = "" },
    { name = "*.yuv" , text = "" },

    # Audio
    { name = "*.aac" , text = "" },
    { name = "*.au"  , text = "" },
    { name = "*.flac", text = "" },
    { name = "*.m4a" , text = "" },
    { name = "*.mid" , text = "" },
    { name = "*.midi", text = "" },
    { name = "*.mka" , text = "" },
    { name = "*.mp3" , text = "" },
    { name = "*.mpc" , text = "" },
    { name = "*.oga" , text = "" },
    { name = "*.ogg" , text = "" },
    { name = "*.opus", text = "" },
    { name = "*.ra"  , text = "" },
    { name = "*.spx" , text = "" },
    { name = "*.wav" , text = "" },
    { name = "*.xspf", text = "" },

    # Documents
    { name = "*.pdf" , text = "", fg = "#b30b00" }, # Printable
    { name = "*.doc" , text = "", fg = "#185abd" }, # Non plaintext docs
    { name = "*.doct", text = "", fg = "#185abd" },
    { name = "*.docx", text = "", fg = "#185abd" },
    { name = "*.dot" , text = "", fg = "#185abd" },
    { name = "*.pom" , text = "󰈩", fg = "#cb4a32" }, # Presentations
    { name = "*.pot" , text = "󰈩", fg = "#cb4a32" },
    { name = "*.potx", text = "󰈩", fg = "#cb4a32" },
    { name = "*.ppm" , text = "󰈩", fg = "#cb4a32" },
    { name = "*.ppmx", text = "󰈩", fg = "#cb4a32" },
    { name = "*.pps" , text = "󰈩", fg = "#cb4a32" },
    { name = "*.ppsx", text = "󰈩", fg = "#cb4a32" },
    { name = "*.ppt" , text = "󰈩", fg = "#cb4a32" },
    { name = "*.pptx", text = "󰈩", fg = "#cb4a32" },
    { name = "*.xlc" , text = "" },
    { name = "*.xlm" , text = "" },
    { name = "*.xls" , text = "" },
    { name = "*.xlsm", text = "" },
    { name = "*.xlsx", text = "" },
    { name = "*.xlt" , text = "" },
    { name = "*.ods" , text = "" },
    { name = "*.ots" , text = "" },
    { name = "*.odg" , text = "󰽉" },

    # Lockfiles
    { name = "*.lock", text = "", fg = "#bbbbbb" },

    # Misc
    { name = "*.bin", text = "" },
    { name = "*.exe", text = "" },
    { name = "*.pkg", text = "" },

    # Dotfiles
    { name = ".DS_Store"     , text = "" },
    { name = ".bashprofile"  , text = "" },
    { name = ".bashrc"       , text = "" },
    { name = ".gitattributes", text = "" },
    { name = ".gitignore"    , text = "" },
    { name = ".gitmodules"   , text = "" },
    { name = ".vimrc"        , text = "" },
    { name = ".zprofile"     , text = "" },
    { name = ".zshenv"       , text = "" },
    { name = ".zshrc"        , text = "" },

    # Named files
    { name = "COPYING"      , text = "󰿃" },
    { name = "Containerfile", text = "󰡨", fg = "#458ee6" },
    { name = "Dockerfile"   , text = "󰡨", fg = "#458ee6" },
    { name = "LICENSE"      , text = "", fg = "#d0bf41" },

    # Default
    { name = "*",  text = "", is = "exec" },
    { name = "*" , text = "" },
    { name = "*/", text = "󰝰", fg = "yellow" },
]

# : }}}
